Fix compilation error: Remove unsupported Diameter property from CoordinateSystemVisual3D
CoordinateSystemVisual3D does not have a Diameter property in HelixToolkit.Wpf.
Removed this line to fix CS0117 compilation error.